### ISSUE TITLE
Нужен гайд

### ISSUE THREAD

**Issue by beznegative** [CyxarikHWG/Gym#2]
Сделай пж как пошагово запустить проект

**Comment by Albedo-13** [comment]
Готово. Если будут какие-то вопросы по поводу установки - пиши. Issue я закрою примерно через неделю-две когда буду уверен, что никаких вопросов не осталось.

Можно поинтересоваться, зачем тебе понадобился проект? Тоже в универ?)

**Comment by beznegative** [comment]
Да. для колледжа нужно потренироваться. Кстати я гайд прочитал, вроде все понятно написано ^). Но у меня опять завал по учебе, я пока что не пробовал установить проект.
